# Generated by Django 4.2.28 on 2026-03-03 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("submissions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SkillScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("overall_score", models.PositiveSmallIntegerField(default=0)),
                ("quality_score", models.PositiveSmallIntegerField(default=0)),
                ("consistency_score", models.PositiveSmallIntegerField(default=0)),
                ("problem_solving_score", models.PositiveSmallIntegerField(default=0)),
                ("improvement_score", models.PositiveSmallIntegerField(default=0)),
                ("last_calculated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_score",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
